project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "analysis/*.qmd"
    - "!analysis/family_size_findability.qmd"
    - "!notes/"

website:
  title: Kincounts
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Analyses
        menu:
          - text: Fertility and sibling relationship
            href: analysis/fert_sibling.qmd
          - text: Fertility modelling with IPUMS data
            href: analysis/fert_model.qmd
          - text: Simulate the number of relatives
            href: analysis/simulate_relatives.qmd
      - text: About
        href: about.qmd
      - text: License
        href: license.qmd
    right:
      - icon: github
        text: Source code
        href: https://github.com/lasisilab/kincounts

execute:
  freeze: auto
  echo: false
  warning: false
  message: false

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    code-fold: true
    number-sections: true
