---
title: "Relationship between Fertility Distribution and Sibling Distribution"
author: "Junhui He"
date: today
---

In this article, we develop a statistical framework for modelling the relationship between the fertility distribution and sibling distribution: Given a fertility distribution, we derive what the resulting sibling distribution would be in the next generation. Specifically, the fertility distribution describes the number of children per parent, while the sibling distribution describes the number of siblings per person in the next generation.

# Fertility Distribution

The number of children per parent in the population is modelled using a fertility distribution, which can be represented by various probability distributions. In this article, we focus on two commonly used distributions for modelling count data: Poisson distribution and zero inflated negative binomial distribution (ZINB).

## Poisson distribution

The Poisson distribution is a popular model for count data, particularly when the mean and variance are equal. However, it may not be very suitable for fertility data, which often exhibit zero-inflation and overdispersion (variance greater than the mean). The Poisson distribution with mean fertility ($\mu$) is defined as: for the number of children $k \geq 0$, $$P(N_{child}=k)=e^{-\mu}\frac{\mu^k}{k!},$$ {#eq-poisson} denoted by $\text{Poisson}(\mu)$. The mean and variance of $\text{Poisson}(\mu)$ are both $\mu$.

## Zero inflated negative binomial distribution

The zero inflated negative binomial distribution with parameters mean fertility ($\mu$), dispersion/size ($\theta$), and zero‑inflation probability ($\pi_0$)---denoted as $\text{ZINB}(\mu, \theta, \pi_0)$---is defined as: for the number of children $k \geq 0$, $$P(N_{child}=k)=\begin{cases}
\pi_0 + (1-\pi_0)p^{\theta} & \text{if } k=0, \\
(1-\pi_0)\binom{k+\theta-1}{k}(1-p)^k p ^{\theta} & \text{if } k \geq 1,
\end{cases}$$ {#eq-zinb} where $p = \frac{\theta}{\mu+\theta}$ is denoted as the success probability. For the negative binomial distribution $\text{NB}(\mu,\theta)$, the mean and variance are $\mu$ and $\mu + \frac{\mu^2}{\theta}$. Therefore, the mean and variance of $\text{ZINB}(\mu, \theta, \pi_0)$ are given by $\mu(1-\pi_0)$ and $\mu(1-\pi_0) + \frac{\mu^2(1-\pi_0)}{\theta}+\mu^2\pi_0(1-\pi_0)$, respectively.

# Sibling distribution

The number of siblings per person in the next generation is modelled using a sibling distribution, which can be derived from the fertility distribution. The sibling distribution describes the probability of an individual having a certain number of siblings, which is directly related to the number of children their parents have.

## Sibship size paradox

A common mistake is that the sibling distribution should be the same as the fertility distribution minus one. However, this is not the case due to the sibship size paradox: individuals with more siblings are more likely to be sampled in the population, leading to a bias in the observed sibling distribution compared to the underlying fertility distribution. 

For example, if we have a population $2N_0$ where $50\%$ of parents have 0 children, $25\%$ of parents have 1 child, and $25\%$ of parents have 2 children, the fertility distribution is $P(N_{child}=0)=0.5$, $P(N_{child}=1)=0.25$, and $P(N_{child}=2)=0.25$. Thus, in the next generation, the population size is $$N_1 = 0.5N_0 \cdot 0 + 0.25N_0 \cdot 1 + 0.25N_0 \cdot 2 = 0.75N_0.$$ And $0.25N_0 \cdot 1$ individuals have 0 siblings, $0.25N_0 \cdot 2$ individuals have 1 sibling. Therefore, the sibling distribution is $$P(N_{sib}=0)=\frac{0.25N_0}{0.75N_0}=\frac{1}{3},\quad P(N_{sib}=1)=\frac{0.25N_0 \cdot 2}{0.75N_0}=\frac{2}{3}.$$

To conclude, most people come from large families even when most families are small, because the number of siblings is weighted by family size. Formally, the relationship between the fertility distribution and sibling distribution can be expressed as follows: Let $N_{child}$ be the random variable representing the number of children per parent, and $N_{sib}$ be the random variable representing the number of siblings per person in the next generation. Then, for any count $k \geq 0$, the probability that an individual has $k$ siblings is proportional to the probability that their mother has $k+1$ children, multiplied by the number of ways the individual could be one of those children. Therefore, we have: $$P(N_{sib}=k) \propto (k+1)P(N_{child}=k+1).$$ {#eq-sibship} This relationship holds for any fertility distribution, and the sibling distribution can be derived accordingly.

## Sibling distribution for different fertility distributions

In this section, we derive the sibling distribution for the two fertility distributions discussed above: Poisson distribution and zero inflated negative binomial distribution, using the relationship established in the previous section.

### Fertility distribution: Poisson distribution

If the fertility distribution is $\text{Poisson}(\mu)$, then the sibling distribution is given by: for a count $k \geq 0$, 
$$\begin{equation}
\begin{split}
P(N_{sib}=k) & \propto (k+1)P(N_{child}=k+1) \\
& \propto (k+1)e^{-\mu}\frac{\mu^{k+1}}{(k+1)!} \\
& = e^{-\mu}\frac{\mu^{k+1}}{k!}\propto e^{-\mu}\frac{\mu^k}{k!}, \\
\end{split}
\end{equation}
$$ {#eq-sibship-poisson} which is also a Poisson distribution with mean $\mu$.

### Fertility distribution: Zero inflated negative binomial distribution

If the fertility distribution is $\text{ZINB}(\mu, \theta, \pi_0)$, then the sibling distribution is given by: for a count $k \geq 0$, $$\begin{equation}
\begin{split}
P(N_{sib}=k) & \propto (k+1)P(N_{child}=k+1) \\
& \propto (1-\pi_0)(k+1)\binom{k+\theta}{k+1}(1-p)^{k+1} p^{\theta} \\
& \propto \frac{\theta(1-p)}{p} \frac{(k+\theta)!}{k!\theta!}(1-p)^k p^{\theta+1} \\
& \propto \binom{k+\theta}{k}(1-p)^k p^{\theta+1}, \\
\end{split}
\end{equation}$$ {#eq-sibship-zinb} where $p = \frac{\theta}{\mu+\theta}$. Therefore, the sibling distribution is a negative binomial distribution with parameters mean fertility ($\frac{\mu(\theta+1)}{\theta}$), dispersion/size ($\theta+1$), denoted as $\text{NB}(\frac{\mu(\theta+1)}{\theta}, \theta+1)$. The variance is $\frac{\mu(\theta+1)}{\theta} + \frac{\mu^2(\theta+1)}{\theta^2}$.